### ISSUE TITLE
regarding number of classes and the data augmentation mechanism

### ISSUE THREAD

**Issue by wenouyang** [haithamkhedr/Semantic-Segmentation#1]
Hi, thanks for sharing the code. I have a question regarding the data set itself. Some ground truth images have some pixels marked as black. What do those pixels represent? My understanding is that this should be a two-class segmentation problem, background and road.

Secondly, what kind of data augmentation methods you have used?

**Comment by haithamkhedr** [comment]
The black pixels represent the other side of the road (opposite direction), so actually there are 3 classes. But, there are few samples and they are noisy so I removed this class and considered that it belongs to class 'road'.
Regarding augmentation, its's tricky to augment the data as you have to do some transformations on the labels too (can be done but not easy). It's mentioned in the paper cited, however it is said that it didn't enhance the performance.

**Comment by wenouyang** [comment]
Thanks for the reply, so the current implementation does not include augmentation. Is that right?

**Comment by haithamkhedr** [comment]
Yeah, there is no augmentation
